name: OF_PIN
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex
  - aiofiles
  - aiosqlite
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - babel
  - backcall
  - beautifulsoup4
  - blas
  - bleach
  - brotli
  - brotli-bin
  - brotlipy
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - comm
  - contourpy
  - cryptography
  - cycler
  - cyrus-sasl
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - expat
  - fontconfig
  - fonttools
  - freetype
  - giflib
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - json5
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_fileid
  - jupyter_server_ydoc
  - jupyter_ydoc
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libclang13
  - libcups
  - libdeflate
  - libedit
  - libevent
  - libffi
  - libgcc-ng
  - libgomp
  - libllvm14
  - libpng
  - libpq
  - libsodium
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libxslt
  - lxml
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - mysql
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - ply
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - pytz
  - pyyaml
  - pyzmq
  - qt-main
  - qt-webengine
  - qtconsole
  - qtpy
  - qtwebkit
  - readline
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - send2trash
  - setuptools
  - sip
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - tbb
  - terminado
  - tinycss2
  - tk
  - toml
  - tomli
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - xz
  - y-py
  - yaml
  - ypy-websocket
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - accelerate==0.26.1
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - annotated-types==0.5.0
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - arrow==1.2.3
    - async-timeout==4.0.3
    - backoff==2.2.1
    - blessed==1.20.0
    - braceexpand==0.1.7
    - click==8.1.7
    - cmake==3.27.2
    - croniter==1.4.1
    - cython==3.0.5
    - dateutils==0.6.12
    - decord==0.6.0
    - deepdiff==6.3.1
    - diffusers==0.26.0
    - docker-pycreds==0.4.0
    - einops==0.6.1
    - einops-exts==0.0.4
    - fairscale==0.4.13
    - fastapi==0.101.1
    - filelock==3.12.2
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - ftfy==6.1.1
    - gitdb==4.0.10
    - gitpython==3.1.32
    - gpustat==1.1
    - h11==0.14.0
    - huggingface-hub==0.20.3
    - imageio==2.33.1
    - inquirer==3.1.3
    - iopath==0.1.10
    - itsdangerous==2.1.2
    - joblib==1.3.2
    - lazy-loader==0.3
    - lightning==2.0.7
    - lightning-cloud==0.5.37
    - lightning-utilities==0.9.0
    - lit==16.0.6
    - lvis==0.5.3
    - markdown-it-py==3.0.0
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - networkx==3.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-ml-py==12.535.77
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - omegaconf==2.3.0
    - open-clip-torch==2.23.0
    - opencv-python==4.8.0.76
    - ordered-set==4.1.0
    - pandas==2.0.3
    - pathtools==0.1.2
    - peft==0.7.1
    - portalocker==2.8.2
    - protobuf==3.20.3
    - pycocotools==2.0.7
    - pydantic==2.1.1
    - pydantic-core==2.4.0
    - pyjwt==2.8.0
    - python-editor==1.0.4
    - python-multipart==0.0.6
    - pytorch-lightning==2.0.7
    - readchar==4.0.5
    - regex==2023.8.8
    - rich==13.5.2
    - safetensors==0.3.2
    - scikit-image==0.22.0
    - scikit-learn==1.3.0
    - scipy==1.11.2
    - sentencepiece==0.1.99
    - sentry-sdk==1.29.2
    - setproctitle==1.3.2
    - smmap==5.0.0
    - starlette==0.27.0
    - starsessions==1.3.0
    - sympy==1.12
    - tensorboardx==2.6.2.2
    - threadpoolctl==3.2.0
    - tifffile==2023.12.9
    - timm==0.4.12
    - tokenizers==0.13.3
    - torch==2.0.1
    - torchaudio==2.0.2
    - torchmetrics==1.0.3
    - torchvision==0.15.2
    - tqdm==4.66.1
    - transformers==4.33.2
    - triton==2.0.0
    - tzdata==2023.3
    - uvicorn==0.23.2
    - wandb==0.15.8
    - webdataset==0.2.86
    - websockets==11.0.3
    - yarl==1.9.2
